services:
  - type: web
    name: cookbook-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn cookbook.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: cookbook-web.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://cookbook-web.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: cookbook-db
          property: connectionString

databases:
  - name: cookbook-db
    plan: free
